CREATE TABLE JobTypes (
    JobTypeID INT PRIMARY KEY AUTO_INCREMENT,
    JobTypeCode VARCHAR(20) UNIQUE NOT NULL,
    JobTypeName VARCHAR(100) NOT NULL,
    Description TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
