CREATE TABLE Personnel (
    PersonnelID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    WorkID VARCHAR(50) UNIQUE NOT NULL,
    IDNumber VARCHAR(255) UNIQUE,
    Gender ENUM('Male', 'Female', 'Other'),
    DateOfBirth DATE,
    Nationality VARCHAR(100),
    ContactNumber VARCHAR(50),
    Email VARCHAR(255) UNIQUE,
    EmergencyContactName VARCHAR(255),
    EmergencyContactPhone VARCHAR(50),
    MainCompanyID INT NOT NULL,
    SubCompanyID INT,
    Department VARCHAR(100),
    JobTitle VARCHAR(100),
    EmploymentType ENUM('FullTime', 'PartTime', 'Contract'),
    TSMCStartDate DATE,
    CurrentStatus ENUM('Active', 'Inactive', 'OnLeave', 'Newcomer', 'Terminated') DEFAULT 'Active',
    HealthGrade VARCHAR(50),
    SafetyRecordSummary TEXT,
    ProfilePhotoPath VARCHAR(255),
    BloodType VARCHAR(10),
    Address TEXT,
    Remarks TEXT,
    UserID INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
